# Generated by Django 4.1 on 2024-11-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TipoProducto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproducto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
