# Generated by Django 4.1 on 2024-11-19 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producto',
            table='producto_producto',
        ),
    ]
