# Generated by Django 4.1 on 2024-11-20 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detallePedido', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallepedido',
            old_name='id_detalle_pedido',
            new_name='id',
        ),
    ]
